import { useState } from "react";
import { Download, FileText, Loader2, Share2, ShieldCheck, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Field, GhostButton, PrimaryButton, inputClass } from "@/components/policies/ui";
import { SectionHeader, SubHeading, Toggle } from "@/components/settings/SettingsSidebar";
import { useSettings } from "@/hooks/useSettings";
import { settingsApi } from "@/lib/settings";

const DATA_TYPES = ["All data", "Credits", "Usage", "Conversions", "Sync history"];
const RANGES = ["Last 7 days", "Last 30 days", "Last 90 days", "All time"];
const FORMATS = ["CSV", "JSON", "XLSX"];

export function ExportSection() {
  const { exports, saving, createExport, clearExports, run } = useSettings();
  const [dataType, setDataType] = useState(DATA_TYPES[0]!);
  const [range, setRange] = useState(RANGES[1]!);
  const [format, setFormat] = useState(FORMATS[0]!);
  const [include, setInclude] = useState({
    buckets: true,
    usage: true,
    conversions: true,
    sync: true,
    personal: false,
  });

  const download = (name: string) => {
    const blob = new Blob([`# ${name}\nGenerated by AI Credit Bank (demo export)\n`], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = name;
    link.click();
    URL.revokeObjectURL(url);
    toast.success("📊 Download started");
  };

  return (
    <div className="space-y-6">
      <SectionHeader
        icon={<Share2 size={18} />}
        title="Export data"
        description="Download your data for analysis or backup purposes."
      />

      <SubHeading>Export options</SubHeading>
      <div className="space-y-4 rounded-xl border border-vault-border bg-vault-bg/40 p-4">
        <div className="grid gap-4 sm:grid-cols-3">
          <Field label="Data type">
            <select className={inputClass} value={dataType} onChange={(e) => setDataType(e.target.value)}>
              {DATA_TYPES.map((t) => (
                <option key={t}>{t}</option>
              ))}
            </select>
          </Field>
          <Field label="Date range">
            <select className={inputClass} value={range} onChange={(e) => setRange(e.target.value)}>
              {RANGES.map((r) => (
                <option key={r}>{r}</option>
              ))}
            </select>
          </Field>
          <Field label="Format">
            <select className={inputClass} value={format} onChange={(e) => setFormat(e.target.value)}>
              {FORMATS.map((f) => (
                <option key={f}>{f}</option>
              ))}
            </select>
          </Field>
        </div>
        <div>
          <p className="text-xs font-medium tracking-wide text-vault-muted uppercase">Include</p>
          <div className="mt-2">
            <Toggle
              label="Credit buckets"
              checked={include.buckets}
              onChange={(v) => setInclude({ ...include, buckets: v })}
            />
            <Toggle
              label="Usage transactions"
              checked={include.usage}
              onChange={(v) => setInclude({ ...include, usage: v })}
            />
            <Toggle
              label="Conversion history"
              checked={include.conversions}
              onChange={(v) => setInclude({ ...include, conversions: v })}
            />
            <Toggle label="Sync history" checked={include.sync} onChange={(v) => setInclude({ ...include, sync: v })} />
            <Toggle
              label="Personal information"
              hint="Includes profile fields and email address"
              checked={include.personal}
              onChange={(v) => setInclude({ ...include, personal: v })}
            />
          </div>
        </div>
      </div>

      <SubHeading>Available exports</SubHeading>
      <div className="space-y-3 rounded-xl border border-vault-border bg-vault-bg/40 p-4">
        <ul className="divide-y divide-vault-border">
          {exports.map((file) => (
            <li key={file.id} className="flex flex-wrap items-center gap-3 py-2.5 text-sm">
              <FileText size={16} className="text-vault-blue" />
              <span className="min-w-0 flex-1 truncate text-vault-foreground">{file.name}</span>
              <span className="text-xs text-vault-faint">{file.size}</span>
              <button
                type="button"
                onClick={() => download(file.name)}
                className="inline-flex items-center gap-1.5 rounded-lg border border-vault-border px-2.5 py-1.5 text-xs text-vault-muted transition hover:text-vault-foreground"
              >
                <Download size={13} />
                Download
              </button>
            </li>
          ))}
          {exports.length === 0 && <li className="py-3 text-sm text-vault-faint">No exports yet.</li>}
        </ul>
        <div className="flex flex-wrap gap-3">
          <GhostButton onClick={() => void createExport({ dataType, format })} disabled={saving}>
            Generate new export
          </GhostButton>
          <GhostButton onClick={() => void clearExports()} disabled={saving || exports.length === 0}>
            <Trash2 size={15} />
            Clear history
          </GhostButton>
        </div>
      </div>

      <SubHeading>Account data</SubHeading>
      <div className="space-y-3 rounded-xl border border-vault-border bg-vault-bg/40 p-4">
        <p className="flex items-center gap-2 text-sm text-vault-foreground">
          <ShieldCheck size={16} className="text-vault-teal" />
          Request all my data (GDPR)
        </p>
        <p className="text-xs text-vault-faint">
          Export includes all personal information. We email a secure link within 24 hours.
        </p>
        <GhostButton
          onClick={() => void run(() => settingsApi.requestGdprExport(), "📊 Data export requested")}
          disabled={saving}
        >
          Request data export
        </GhostButton>
      </div>

      <div className="flex flex-wrap gap-3">
        <PrimaryButton onClick={() => void createExport({ dataType, format })} disabled={saving}>
          {saving && <Loader2 size={15} className="animate-spin" />}
          Export now
        </PrimaryButton>
        <GhostButton onClick={() => toast.success("🗓️ Weekly export scheduled")}>Schedule export</GhostButton>
      </div>
    </div>
  );
}
